mutation login($email: String, $passwd: String) {
  login(email: $email, passwd: $passwd) {
    accessToken
    startAt
    endAt
    workingType
    lastLogin
  }
}

query checkUserIdDuplication($userId: String!) {
  checkUserIdDuplication(userId: $userId)
}

mutation logout {
  logout {
    employeeId
    userId
    name
    department {
      departmentName
    }
    email
  }
}

mutation refresh {
  refresh {
    accessToken
    startAt
    endAt
    workingType
  }
}

mutation goToWork {
  goToWork {
    employeeId
    userId
    name
    department {
      departmentId
      departmentName
    }
    workingDate
    workingType
    startAt
    endAt
  }
}

mutation leaveWork {
  leaveWork {
    employeeId
    userId
    name
    department {
      departmentId
      departmentName
    }
    workingDate
    workingType
    startAt
    endAt
  }
}

subscription attended {
  attended {
    employeeId
    name
    department {
      departmentId
      departmentName
    }
    userId
    workingDate
    workingType
    startAt
    endAt
  }
}
