mutation login($userId: String, $passwd: String) {
  login(userId: $userId, passwd: $passwd) {
    accessToken
    startAt
    endAt
    workingType
  }
}

mutation logout {
  logout {
    employeeId
    userId
    employeeName
    department {
      departmentName
    }
    email
  }
}

mutation refresh {
  refresh {
    accessToken
    startAt
    endAt
    workingType
  }
}

mutation goToWork {
  goToWork {
    employeeId
    userId
    employeeName
    department {
      departmentId
      departmentName
    }
    workingDate
    workingType
    startAt
    endAt
  }
}

mutation leaveWork {
  leaveWork {
    employeeId
    userId
    employeeName
    department {
      departmentId
      departmentName
    }
    workingDate
    workingType
    startAt
    endAt
  }
}

subscription attended {
  attended {
    employeeId
    employeeName
    department {
      departmentId
      departmentName
    }
    userId
    workingDate
    workingType
    startAt
    endAt
  }
}
