query getAllEmployee {
  employees {
    employeeId
    userId
    employeeName
    department {
      departmentId
      departmentName
    }
  }
  departments {
    departmentId
    departmentName
  }
}

query getEmployeeWorking($dt: String) {
  employeeWorking(dt: $dt) {
    employeeId
    employeeName
    department {
      departmentId
      departmentName
    }
    userId
    workingDate
    workingType
    startAt
    endAt
  }
}
