query getAllEmployee {
  employees {
    employeeId
    userId
    name
    position
    department {
      departmentId
      departmentName
    }
    contractType
    phone
    email
    startDate
    photoUrl
  }
  departments {
    departmentId
    departmentName
  }
}

query getEmployee($userId: String) {
  employee(userId: $userId) {
    employeeId
    userId
    name
    position
    department {
      departmentId
      departmentName
    }
    contractType
    phone
    email
    startDate
    photoUrl
  }
}

query getAllDepartments {
  departments {
    departmentId
    departmentName
  }
}

query getEmployeeWorking($dt: String) {
  employeeWorking(dt: $dt) {
    employeeId
    name
    position
    department {
      departmentId
      departmentName
    }
    userId
    workingDate
    workingType
    startAt
    endAt
  }
}

query getEmployeeWorkingConditional($searchCondition: EmployeeWorkingCondition) {
  employeeWorkingConditional(searchCondition: $searchCondition) {
    employeeId
    name
    position
    department {
      departmentId
      departmentName
    }
    userId
    workingDate
    workingType
    startAt
    endAt
  }
}

mutation addEmployee($input: EmployeeInput!) {
  addEmployee(input: $input) {
    userId
    name
    position
    email
    department {
      departmentId
      departmentName
    }
    contractType
    phone
    startDate
  }
}

query getCodes($parents: [String]) {
  codes(parents: $parents) {
    parentCode
    parentName
    codes {
      code
      name
    }
  }
}
